# Generated by Django 5.1.7 on 2025-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsAppart',
            fields=[
                ('numapp', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('design', models.CharField(blank=True, max_length=100)),
                ('loyer', models.IntegerField(max_length=100)),
            ],
        ),
    ]
