# Generated by Django 5.1.7 on 2025-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsappart',
            name='design',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
