# Generated by Django 5.1.7 on 2025-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_alter_detailsappart_loyer_alter_detailsappart_numapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
    ]
