# Generated by Django 5.1.7 on 2025-04-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0004_detailsappart_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aths',
        ),
        migrations.RemoveField(
            model_name='detailsappart',
            name='owner',
        ),
    ]
